services:
  - type: web
    name: tooth-brushing-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
